# Generated by Django 4.1.1 on 2022-09-29 01:30

from django.db import migrations


def populate_status(apps, schemaeditor):
    entries = {
        "published": "A post that appears on the site (to all users).",
        "draft": "A post that is being workrd on, or not ready to be viewed.",
        "archived": "A post that no longer appears on the site."
    }
    Status = apps.get_model("posts", "Satus")
    for name, desc in entries.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_satus'),
    ]

    operations = [migrations.RunPython(populate_status)]
